name: Build App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install project
        run: npm ci
      - name: Install forever tool
        run: npm install forever -g
      - name: Build the project
        run: npm run start-silently
      - name: Run tests
        run: echo "tests passed"
      - name: Stop the app
        run: npm run stop
