name: Build & Run API health checks

on:
  pull_request:
    branches: 
      - master
    paths: ['package-lock.json', 'package.json']

jobs:
  #build_and_test_from_master :
  build_and_test_from_pr:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo from PR branch
        uses: actions/checkout@v4
      - name: Print name of pulled branch
        run: echo running on branch ${GITHUB_HEAD_REF}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install project
        run: npm ci
      - name: Install forever tool
        run: npm install forever -g
      - name: Build the project
        run: npm run start-silently
      - name: Checkout remote branch with API tests
        uses: actions/checkout@v4
        with: 
          repository: fiddlerta/gatling-maven-tests-java
          path: api-tests
      - name: Check 'api-tests' folder content
        run: |
          ls -a $GITHUB_ACTION_PATH/api-tests"
      - name: Run gatling API tests
        uses: liatrio/run-gatling@v1.2.0
        with:
          pomPath: $GITHUB_ACTION_PATH/api-tests
      - name: Stop the app
        run: npm run stop
